/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: ['class', '[data-theme="graphite-dark"]'],
  theme: {
    extend: {
      colors: {
        vb: {
          bg: 'var(--vb-bg)',
          surface: 'var(--vb-surface)',
          'surface-muted': 'var(--vb-surface-muted)',
          chip: 'var(--vb-chip)',
          border: 'var(--vb-border)',
          'border-strong': 'var(--vb-border-strong)',
          shadow: 'var(--vb-shadow)',
          text: 'var(--vb-text)',
          'text-muted': 'var(--vb-text-muted)',
          'text-subtle': 'var(--vb-text-subtle)',
          accent: 'var(--vb-accent)',
          'accent-hover': 'var(--vb-accent-hover)',
          'accent-light': 'var(--vb-accent-light)',
          'input-bg': 'var(--vb-input-bg)',
          'input-border': 'var(--vb-input-border)',
          'input-focus-border': 'var(--vb-input-focus-border)',
          'card-bg': 'var(--vb-card-bg)',
          'card-hover-bg': 'var(--vb-card-hover-bg)',
          'glass-light': 'var(--vb-glass-light)',
          'glass-lighter': 'var(--vb-glass-lighter)',
          'terminal-bg': 'var(--vb-terminal-bg)',
          'terminal-border': 'var(--vb-terminal-border)',
          'terminal-focus': 'var(--vb-terminal-focus)',
          'terminal-text': 'var(--vb-terminal-text)',
          'terminal-prompt': 'var(--vb-terminal-prompt)',
          'terminal-prefix': 'var(--vb-terminal-prefix)',
          'terminal-hint': 'var(--vb-terminal-hint)',
          'terminal-caret': 'var(--vb-terminal-caret)',
          success: 'var(--vb-success)',
          'success-bg': 'var(--vb-success-bg)',
          warning: 'var(--vb-warning)',
          'warning-bg': 'var(--vb-warning-bg)',
          error: 'var(--vb-error)',
          'error-bg': 'var(--vb-error-bg)',
        },
      },
      fontFamily: {
        ui: ['var(--vb-font-ui)'],
        mono: ['var(--vb-font-mono)'],
      },
      borderRadius: {
        'xs': 'var(--vb-radius-xs)',
        'sm': 'var(--vb-radius-sm)',
        'md': 'var(--vb-radius-md)',
        'lg': 'var(--vb-radius-lg)',
        'xl': 'var(--vb-radius-xl)',
        'full': 'var(--vb-radius-full)',
      },
      boxShadow: {
        'glass-sm': 'var(--vb-shadow-sm)',
        'glass-md': 'var(--vb-shadow)',
        'glass-lg': 'var(--vb-shadow-lg)',
        'inset': 'var(--vb-shadow-inset)',
      },
      transitionTimingFunction: {
        'spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        'smooth': 'cubic-bezier(0.25, 0.46, 0.45, 0.94)',
        'out': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      transitionDuration: {
        'fast': '150ms',
        'normal': '250ms',
        'slow': '350ms',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'slide-up': {
          '0%': { transform: 'translateY(12px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-down': {
          '0%': { transform: 'translateY(-12px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'scale-in': {
          '0%': { transform: 'scale(0.96)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        'spring-in': {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '60%': { transform: 'scale(1.02)', opacity: '1' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        'shimmer': {
          '0%': { backgroundPosition: '-1000px 0' },
          '100%': { backgroundPosition: '1000px 0' },
        },
        'pulse-subtle': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
        'breathe': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.25s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
        'slide-up': 'slide-up 0.35s cubic-bezier(0.34, 1.56, 0.64, 1)',
        'slide-down': 'slide-down 0.25s cubic-bezier(0.34, 1.56, 0.64, 1)',
        'scale-in': 'scale-in 0.25s cubic-bezier(0.34, 1.56, 0.64, 1)',
        'spring-in': 'spring-in 0.35s cubic-bezier(0.34, 1.56, 0.64, 1)',
        'shimmer': 'shimmer 2s linear infinite',
        'pulse-subtle': 'pulse-subtle 2s cubic-bezier(0.4, 0, 0.2, 1) infinite',
        'breathe': 'breathe 2s cubic-bezier(0.4, 0, 0.2, 1) infinite',
      },
    },
  },
  plugins: [],
}
