use serde::{Deserialize, Serialize};
use tauri::State;
use vb_task::AgentToolKind;

use crate::app_state::AppState;

const CATALOG_VERSION: u32 = 3;

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ToolCommandProviderKind {
    Claude,
    Codex,
    Gemini,
    Shell,
    Unknown,
    Any,
}

impl From<Option<AgentToolKind>> for ToolCommandProviderKind {
    fn from(value: Option<AgentToolKind>) -> Self {
        match value {
            Some(AgentToolKind::Claude) => Self::Claude,
            Some(AgentToolKind::Codex) => Self::Codex,
            Some(AgentToolKind::Gemini) => Self::Gemini,
            Some(AgentToolKind::Shell) => Self::Shell,
            Some(AgentToolKind::Unknown) | None => Self::Any,
        }
    }
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ToolCommandKind {
    Semantic,
    ProviderNative,
    BundledSkill,
    SettingsEntry,
    LaunchProfile,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ToolCommandFamily {
    BuiltIn,
    BundledSkill,
    WorkspaceAction,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ToolCommandCategory {
    PromptInsert,
    TerminalSubmit,
    LaunchTool,
    OpenSettings,
    McpHelper,
    SlashTemplate,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ToolCommandSurfaceTarget {
    Terminal,
    WorkspaceUi,
    ToolAdapter,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ToolCommandScopeKind {
    Station,
    Workspace,
    Selection,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ToolCommandPresentation {
    Direct,
    Sheet,
    Navigation,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ToolCommandDangerLevel {
    Safe,
    Confirm,
    Expensive,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ToolCommandArgumentKind {
    Text,
    MultilineText,
    Enum,
    Duration,
    Path,
    Boolean,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ToolCommandArgumentOption {
    pub label: String,
    pub value: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ToolCommandArgument {
    pub name: String,
    pub label: String,
    pub kind: ToolCommandArgumentKind,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub placeholder: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub default_value: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub options: Vec<ToolCommandArgumentOption>,
    #[serde(default)]
    pub required: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ToolCommandExecution {
    InsertText { text: String, submit: bool },
    OpenCommandSheet { command: String, submit: bool },
    LaunchProfile { profile_id: String },
    OpenSettingsModal { section: String },
    OpenChannelStudio,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ToolCommandCatalogStationContext {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub station_id: Option<String>,
    #[serde(default)]
    pub has_terminal_session: bool,
    #[serde(default)]
    pub detached_readonly: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resolved_cwd: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ToolCommandCatalogRequest {
    pub workspace_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_kind: Option<AgentToolKind>,
    #[serde(default)]
    pub station: ToolCommandCatalogStationContext,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ToolCommandCatalogResponse {
    pub workspace_id: String,
    pub catalog_version: u32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_kind: Option<AgentToolKind>,
    pub station: ToolCommandCatalogStationContext,
    pub commands: Vec<ToolCommandCatalogItem>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ToolCommandCatalogItem {
    pub id: String,
    pub label: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub short_label: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub slash_command: Option<String>,
    pub command_family: ToolCommandFamily,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tooltip: Option<String>,
    pub icon: String,
    pub provider_kind: ToolCommandProviderKind,
    pub kind: ToolCommandKind,
    pub category: ToolCommandCategory,
    pub surface_target: ToolCommandSurfaceTarget,
    pub scope_kind: ToolCommandScopeKind,
    pub group: String,
    pub priority: i32,
    pub presentation: ToolCommandPresentation,
    pub danger_level: ToolCommandDangerLevel,
    pub default_pinned: bool,
    pub enabled: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub disabled_reason: Option<String>,
    pub requires_live_session: bool,
    pub supports_detached_window: bool,
    pub supports_parallel_targets: bool,
    pub execution: ToolCommandExecution,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub arguments: Vec<ToolCommandArgument>,
}

fn text_command(
    id: &str,
    label: &str,
    short_label: Option<&str>,
    slash_command: Option<&str>,
    command_family: ToolCommandFamily,
    tooltip: Option<&str>,
    icon: &str,
    provider_kind: ToolCommandProviderKind,
    group: &str,
    priority: i32,
    category: ToolCommandCategory,
    command_text: &str,
    submit: bool,
    danger_level: ToolCommandDangerLevel,
    kind: ToolCommandKind,
    default_pinned: bool,
    enabled: bool,
    disabled_reason: Option<String>,
    requires_live_session: bool,
    supports_parallel_targets: bool,
) -> ToolCommandCatalogItem {
    ToolCommandCatalogItem {
        id: id.to_string(),
        label: label.to_string(),
        short_label: short_label.map(str::to_string),
        slash_command: slash_command.map(str::to_string),
        command_family,
        tooltip: tooltip.map(str::to_string),
        icon: icon.to_string(),
        provider_kind,
        kind,
        category,
        surface_target: ToolCommandSurfaceTarget::Terminal,
        scope_kind: ToolCommandScopeKind::Station,
        group: group.to_string(),
        priority,
        presentation: ToolCommandPresentation::Direct,
        danger_level,
        default_pinned,
        enabled,
        disabled_reason,
        requires_live_session,
        supports_detached_window: true,
        supports_parallel_targets,
        execution: ToolCommandExecution::InsertText {
            text: command_text.to_string(),
            submit,
        },
        arguments: Vec::new(),
    }
}

fn sheet_command(
    id: &str,
    label: &str,
    short_label: Option<&str>,
    slash_command: Option<&str>,
    command_family: ToolCommandFamily,
    tooltip: Option<&str>,
    icon: &str,
    provider_kind: ToolCommandProviderKind,
    group: &str,
    priority: i32,
    category: ToolCommandCategory,
    command_text: &str,
    arguments: Vec<ToolCommandArgument>,
    danger_level: ToolCommandDangerLevel,
    kind: ToolCommandKind,
    default_pinned: bool,
    enabled: bool,
    disabled_reason: Option<String>,
    requires_live_session: bool,
) -> ToolCommandCatalogItem {
    ToolCommandCatalogItem {
        id: id.to_string(),
        label: label.to_string(),
        short_label: short_label.map(str::to_string),
        slash_command: slash_command.map(str::to_string),
        command_family,
        tooltip: tooltip.map(str::to_string),
        icon: icon.to_string(),
        provider_kind,
        kind,
        category,
        surface_target: ToolCommandSurfaceTarget::Terminal,
        scope_kind: ToolCommandScopeKind::Station,
        group: group.to_string(),
        priority,
        presentation: ToolCommandPresentation::Sheet,
        danger_level,
        default_pinned,
        enabled,
        disabled_reason,
        requires_live_session,
        supports_detached_window: true,
        supports_parallel_targets: false,
        execution: ToolCommandExecution::OpenCommandSheet {
            command: command_text.to_string(),
            submit: true,
        },
        arguments,
    }
}

fn session_disabled_reason(
    has_live_session: bool,
    detached_readonly: bool,
    provider_name: &str,
) -> Option<String> {
    if detached_readonly {
        Some("Detached windows are read only".to_string())
    } else if !has_live_session {
        Some(format!("Start a live {provider_name} session first"))
    } else {
        None
    }
}

fn command_sheet_arguments(command: &str) -> Vec<ToolCommandArgument> {
    match command {
        "/effort" => vec![ToolCommandArgument {
            name: "level".to_string(),
            label: "Effort level".to_string(),
            kind: ToolCommandArgumentKind::Enum,
            placeholder: None,
            default_value: Some("auto".to_string()),
            options: vec![
                ToolCommandArgumentOption {
                    label: "Low".to_string(),
                    value: "low".to_string(),
                },
                ToolCommandArgumentOption {
                    label: "Medium".to_string(),
                    value: "medium".to_string(),
                },
                ToolCommandArgumentOption {
                    label: "High".to_string(),
                    value: "high".to_string(),
                },
                ToolCommandArgumentOption {
                    label: "Max".to_string(),
                    value: "max".to_string(),
                },
                ToolCommandArgumentOption {
                    label: "Auto".to_string(),
                    value: "auto".to_string(),
                },
            ],
            required: true,
        }],
        "/model" => vec![ToolCommandArgument {
            name: "model".to_string(),
            label: "Model".to_string(),
            kind: ToolCommandArgumentKind::Text,
            placeholder: Some("model alias or full model name".to_string()),
            default_value: None,
            options: Vec::new(),
            required: true,
        }],
        "/loop" => vec![
            ToolCommandArgument {
                name: "interval".to_string(),
                label: "Interval".to_string(),
                kind: ToolCommandArgumentKind::Duration,
                placeholder: Some("10m".to_string()),
                default_value: Some("10m".to_string()),
                options: Vec::new(),
                required: true,
            },
            ToolCommandArgument {
                name: "prompt".to_string(),
                label: "Prompt".to_string(),
                kind: ToolCommandArgumentKind::MultilineText,
                placeholder: Some("Repeat a prompt or slash command".to_string()),
                default_value: None,
                options: Vec::new(),
                required: true,
            },
        ],
        "/batch" => vec![ToolCommandArgument {
            name: "instruction".to_string(),
            label: "Instruction".to_string(),
            kind: ToolCommandArgumentKind::MultilineText,
            placeholder: Some("Describe the large-scale change".to_string()),
            default_value: None,
            options: Vec::new(),
            required: true,
        }],
        "/add-dir" => vec![ToolCommandArgument {
            name: "directory".to_string(),
            label: "Directory".to_string(),
            kind: ToolCommandArgumentKind::Path,
            placeholder: Some("workspace-relative path".to_string()),
            default_value: None,
            options: Vec::new(),
            required: true,
        }],
        _ => Vec::new(),
    }
}

fn claude_native_commands(
    has_live_session: bool,
    detached_readonly: bool,
) -> Vec<ToolCommandCatalogItem> {
    let write_enabled = has_live_session && !detached_readonly;
    let write_reason = session_disabled_reason(has_live_session, detached_readonly, "Claude");

    vec![
        text_command(
            "claude-new",
            "New conversation",
            Some("/new"),
            Some("/new"),
            ToolCommandFamily::BuiltIn,
            Some("Start a fresh conversation in Claude Code"),
            "plus",
            ToolCommandProviderKind::Claude,
            "session",
            10,
            ToolCommandCategory::SlashTemplate,
            "/new ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            true,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-help",
            "Help",
            Some("/help"),
            Some("/help"),
            ToolCommandFamily::BuiltIn,
            Some("Open Claude Code help"),
            "info",
            ToolCommandProviderKind::Claude,
            "session",
            20,
            ToolCommandCategory::PromptInsert,
            "/help ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            true,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-diff",
            "Diff",
            Some("/diff"),
            Some("/diff"),
            ToolCommandFamily::BuiltIn,
            Some("Show the current diff"),
            "git-diff",
            ToolCommandProviderKind::Claude,
            "session",
            30,
            ToolCommandCategory::PromptInsert,
            "/diff ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            true,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-context",
            "Context",
            Some("/context"),
            Some("/context"),
            ToolCommandFamily::BuiltIn,
            Some("Visualize the current context"),
            "layers",
            ToolCommandProviderKind::Claude,
            "session",
            40,
            ToolCommandCategory::PromptInsert,
            "/context ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            true,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-plan",
            "Plan",
            Some("/plan"),
            Some("/plan"),
            ToolCommandFamily::BuiltIn,
            Some("Enable or inspect plan mode"),
            "clipboard-list",
            ToolCommandProviderKind::Claude,
            "session",
            50,
            ToolCommandCategory::PromptInsert,
            "/plan ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            true,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-status",
            "Status",
            Some("/status"),
            Some("/status"),
            ToolCommandFamily::BuiltIn,
            Some("Show session status"),
            "activity",
            ToolCommandProviderKind::Claude,
            "session",
            60,
            ToolCommandCategory::PromptInsert,
            "/status ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            true,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-agents",
            "Agents",
            Some("/agents"),
            Some("/agents"),
            ToolCommandFamily::BuiltIn,
            Some("List or manage Claude sub-agents"),
            "users",
            ToolCommandProviderKind::Claude,
            "session",
            70,
            ToolCommandCategory::PromptInsert,
            "/agents ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            true,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-mcp",
            "MCP",
            Some("/mcp"),
            Some("/mcp"),
            ToolCommandFamily::BuiltIn,
            Some("Manage MCP servers"),
            "link",
            ToolCommandProviderKind::Claude,
            "session",
            80,
            ToolCommandCategory::PromptInsert,
            "/mcp ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            true,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        sheet_command(
            "claude-effort",
            "Effort",
            Some("/effort"),
            Some("/effort"),
            ToolCommandFamily::BuiltIn,
            Some("Adjust the effort level"),
            "sliders-horizontal",
            ToolCommandProviderKind::Claude,
            "session",
            90,
            ToolCommandCategory::SlashTemplate,
            "/effort",
            command_sheet_arguments("/effort"),
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
        ),
        text_command(
            "claude-effort-max",
            "Effort max",
            Some("/effort max"),
            Some("/effort max"),
            ToolCommandFamily::BuiltIn,
            Some("Set Claude effort level to max"),
            "sliders-horizontal",
            ToolCommandProviderKind::Claude,
            "session",
            100,
            ToolCommandCategory::SlashTemplate,
            "/effort max ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            true,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-clear",
            "Clear conversation",
            Some("/clear"),
            Some("/clear"),
            ToolCommandFamily::BuiltIn,
            Some("Clear the current conversation"),
            "eraser",
            ToolCommandProviderKind::Claude,
            "session",
            110,
            ToolCommandCategory::SlashTemplate,
            "/clear ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-compact",
            "Compact conversation",
            Some("/compact"),
            Some("/compact"),
            ToolCommandFamily::BuiltIn,
            Some("Compact conversation history"),
            "minimize-2",
            ToolCommandProviderKind::Claude,
            "session",
            120,
            ToolCommandCategory::SlashTemplate,
            "/compact ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-config",
            "Configuration",
            Some("/config"),
            Some("/config"),
            ToolCommandFamily::BuiltIn,
            Some("Open Claude Code configuration"),
            "settings",
            ToolCommandProviderKind::Claude,
            "session",
            130,
            ToolCommandCategory::PromptInsert,
            "/config ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        sheet_command(
            "claude-add-dir",
            "Add directory",
            Some("/add-dir"),
            Some("/add-dir"),
            ToolCommandFamily::BuiltIn,
            Some("Add a working directory"),
            "folder-plus",
            ToolCommandProviderKind::Claude,
            "session",
            140,
            ToolCommandCategory::SlashTemplate,
            "/add-dir",
            command_sheet_arguments("/add-dir"),
            ToolCommandDangerLevel::Confirm,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
        ),
        text_command(
            "claude-btw",
            "Side question",
            Some("/btw"),
            Some("/btw"),
            ToolCommandFamily::BuiltIn,
            Some("Ask a side question without interrupting the main thread"),
            "message-square",
            ToolCommandProviderKind::Claude,
            "session",
            150,
            ToolCommandCategory::SlashTemplate,
            "/btw ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-branch",
            "Branch conversation",
            Some("/branch"),
            Some("/branch"),
            ToolCommandFamily::BuiltIn,
            Some("Create a branch of the current conversation"),
            "git-branch",
            ToolCommandProviderKind::Claude,
            "session",
            160,
            ToolCommandCategory::PromptInsert,
            "/branch ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-chrome",
            "Chrome",
            Some("/chrome"),
            Some("/chrome"),
            ToolCommandFamily::BuiltIn,
            Some("Open Claude in Chrome settings"),
            "chrome",
            ToolCommandProviderKind::Claude,
            "session",
            170,
            ToolCommandCategory::PromptInsert,
            "/chrome ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-color",
            "Prompt bar color",
            Some("/color"),
            Some("/color"),
            ToolCommandFamily::BuiltIn,
            Some("Adjust the prompt bar color"),
            "palette",
            ToolCommandProviderKind::Claude,
            "session",
            180,
            ToolCommandCategory::PromptInsert,
            "/color ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-copy",
            "Copy response",
            Some("/copy"),
            Some("/copy"),
            ToolCommandFamily::BuiltIn,
            Some("Copy Claude's last response"),
            "copy",
            ToolCommandProviderKind::Claude,
            "session",
            190,
            ToolCommandCategory::PromptInsert,
            "/copy ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-cost",
            "Usage and cost",
            Some("/cost"),
            Some("/cost"),
            ToolCommandFamily::BuiltIn,
            Some("Show usage and cost details"),
            "coins",
            ToolCommandProviderKind::Claude,
            "session",
            200,
            ToolCommandCategory::PromptInsert,
            "/cost ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-desktop",
            "Desktop handoff",
            Some("/desktop"),
            Some("/desktop"),
            ToolCommandFamily::BuiltIn,
            Some("Continue the current session in Claude Desktop"),
            "monitor-smartphone",
            ToolCommandProviderKind::Claude,
            "session",
            210,
            ToolCommandCategory::PromptInsert,
            "/desktop ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-doctor",
            "Diagnostics",
            Some("/doctor"),
            Some("/doctor"),
            ToolCommandFamily::BuiltIn,
            Some("Run Claude Code diagnostics"),
            "stethoscope",
            ToolCommandProviderKind::Claude,
            "session",
            220,
            ToolCommandCategory::PromptInsert,
            "/doctor ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-exit",
            "Exit",
            Some("/exit"),
            Some("/exit"),
            ToolCommandFamily::BuiltIn,
            Some("Exit the current Claude Code session"),
            "log-out",
            ToolCommandProviderKind::Claude,
            "session",
            230,
            ToolCommandCategory::PromptInsert,
            "/exit ",
            true,
            ToolCommandDangerLevel::Confirm,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-export",
            "Export conversation",
            Some("/export"),
            Some("/export"),
            ToolCommandFamily::BuiltIn,
            Some("Export the current conversation"),
            "file-text",
            ToolCommandProviderKind::Claude,
            "session",
            240,
            ToolCommandCategory::PromptInsert,
            "/export ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-fast",
            "Fast mode",
            Some("/fast"),
            Some("/fast"),
            ToolCommandFamily::BuiltIn,
            Some("Toggle fast mode"),
            "zap",
            ToolCommandProviderKind::Claude,
            "session",
            250,
            ToolCommandCategory::PromptInsert,
            "/fast ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-feedback",
            "Feedback",
            Some("/feedback"),
            Some("/feedback"),
            ToolCommandFamily::BuiltIn,
            Some("Send feedback about Claude Code"),
            "info",
            ToolCommandProviderKind::Claude,
            "session",
            260,
            ToolCommandCategory::PromptInsert,
            "/feedback ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-hooks",
            "Hooks",
            Some("/hooks"),
            Some("/hooks"),
            ToolCommandFamily::BuiltIn,
            Some("Manage Claude Code hooks"),
            "workflow",
            ToolCommandProviderKind::Claude,
            "session",
            270,
            ToolCommandCategory::PromptInsert,
            "/hooks ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-ide",
            "IDE integration",
            Some("/ide"),
            Some("/ide"),
            ToolCommandFamily::BuiltIn,
            Some("Manage IDE integrations"),
            "monitor-smartphone",
            ToolCommandProviderKind::Claude,
            "session",
            280,
            ToolCommandCategory::PromptInsert,
            "/ide ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-init",
            "Initialize repository",
            Some("/init"),
            Some("/init"),
            ToolCommandFamily::BuiltIn,
            Some("Initialize Claude Code in this repository"),
            "sparkles",
            ToolCommandProviderKind::Claude,
            "session",
            290,
            ToolCommandCategory::PromptInsert,
            "/init ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-install-github-app",
            "Install GitHub app",
            Some("/install-github-app"),
            Some("/install-github-app"),
            ToolCommandFamily::BuiltIn,
            Some("Set up Claude GitHub Actions for a repository"),
            "external",
            ToolCommandProviderKind::Claude,
            "session",
            300,
            ToolCommandCategory::PromptInsert,
            "/install-github-app ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-install-slack-app",
            "Install Slack app",
            Some("/install-slack-app"),
            Some("/install-slack-app"),
            ToolCommandFamily::BuiltIn,
            Some("Install the Claude Slack app"),
            "external",
            ToolCommandProviderKind::Claude,
            "session",
            310,
            ToolCommandCategory::PromptInsert,
            "/install-slack-app ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-login",
            "Sign in",
            Some("/login"),
            Some("/login"),
            ToolCommandFamily::BuiltIn,
            Some("Sign in to Claude Code"),
            "log-in",
            ToolCommandProviderKind::Claude,
            "session",
            320,
            ToolCommandCategory::PromptInsert,
            "/login ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-logout",
            "Sign out",
            Some("/logout"),
            Some("/logout"),
            ToolCommandFamily::BuiltIn,
            Some("Sign out of Claude Code"),
            "log-out",
            ToolCommandProviderKind::Claude,
            "session",
            330,
            ToolCommandCategory::PromptInsert,
            "/logout ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-memory",
            "Memory",
            Some("/memory"),
            Some("/memory"),
            ToolCommandFamily::BuiltIn,
            Some("Manage Claude Code memory"),
            "brain",
            ToolCommandProviderKind::Claude,
            "session",
            340,
            ToolCommandCategory::PromptInsert,
            "/memory ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-mobile",
            "Mobile handoff",
            Some("/mobile"),
            Some("/mobile"),
            ToolCommandFamily::BuiltIn,
            Some("Show a QR code to continue on mobile"),
            "monitor-smartphone",
            ToolCommandProviderKind::Claude,
            "session",
            350,
            ToolCommandCategory::PromptInsert,
            "/mobile ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        sheet_command(
            "claude-model",
            "Model",
            Some("/model"),
            Some("/model"),
            ToolCommandFamily::BuiltIn,
            Some("Switch the active model"),
            "cpu",
            ToolCommandProviderKind::Claude,
            "session",
            360,
            ToolCommandCategory::SlashTemplate,
            "/model",
            command_sheet_arguments("/model"),
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
        ),
        text_command(
            "claude-permissions",
            "Permissions",
            Some("/permissions"),
            Some("/permissions"),
            ToolCommandFamily::BuiltIn,
            Some("Manage allow and deny tool permission rules"),
            "shield-check",
            ToolCommandProviderKind::Claude,
            "session",
            370,
            ToolCommandCategory::PromptInsert,
            "/permissions ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-plugin",
            "Plugins",
            Some("/plugin"),
            Some("/plugin"),
            ToolCommandFamily::BuiltIn,
            Some("Manage Claude Code plugins"),
            "puzzle",
            ToolCommandProviderKind::Claude,
            "session",
            380,
            ToolCommandCategory::PromptInsert,
            "/plugin ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-release-notes",
            "Release notes",
            Some("/release-notes"),
            Some("/release-notes"),
            ToolCommandFamily::BuiltIn,
            Some("Show Claude Code release notes"),
            "book-open",
            ToolCommandProviderKind::Claude,
            "session",
            390,
            ToolCommandCategory::PromptInsert,
            "/release-notes ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-rename",
            "Rename conversation",
            Some("/rename"),
            Some("/rename"),
            ToolCommandFamily::BuiltIn,
            Some("Rename the current conversation"),
            "edit-3",
            ToolCommandProviderKind::Claude,
            "session",
            400,
            ToolCommandCategory::PromptInsert,
            "/rename ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-resume",
            "Resume conversation",
            Some("/resume"),
            Some("/resume"),
            ToolCommandFamily::BuiltIn,
            Some("Resume a previous conversation"),
            "play",
            ToolCommandProviderKind::Claude,
            "session",
            410,
            ToolCommandCategory::PromptInsert,
            "/resume ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-rewind",
            "Rewind",
            Some("/rewind"),
            Some("/rewind"),
            ToolCommandFamily::BuiltIn,
            Some("Restore code or conversation to a previous point"),
            "rewind",
            ToolCommandProviderKind::Claude,
            "session",
            420,
            ToolCommandCategory::PromptInsert,
            "/rewind ",
            true,
            ToolCommandDangerLevel::Confirm,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-sandbox",
            "Sandbox",
            Some("/sandbox"),
            Some("/sandbox"),
            ToolCommandFamily::BuiltIn,
            Some("Inspect or configure sandbox mode"),
            "shield",
            ToolCommandProviderKind::Claude,
            "session",
            430,
            ToolCommandCategory::PromptInsert,
            "/sandbox ",
            true,
            ToolCommandDangerLevel::Confirm,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-schedule",
            "Schedule tasks",
            Some("/schedule"),
            Some("/schedule"),
            ToolCommandFamily::BuiltIn,
            Some("Create a scheduled task"),
            "repeat",
            ToolCommandProviderKind::Claude,
            "session",
            440,
            ToolCommandCategory::PromptInsert,
            "/schedule ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-skills",
            "Skills",
            Some("/skills"),
            Some("/skills"),
            ToolCommandFamily::BuiltIn,
            Some("List available skills"),
            "book-open",
            ToolCommandProviderKind::Claude,
            "session",
            450,
            ToolCommandCategory::PromptInsert,
            "/skills ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-stats",
            "Stats",
            Some("/stats"),
            Some("/stats"),
            ToolCommandFamily::BuiltIn,
            Some("Show Claude Code usage statistics"),
            "bar-chart-3",
            ToolCommandProviderKind::Claude,
            "session",
            460,
            ToolCommandCategory::PromptInsert,
            "/stats ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-terminal-setup",
            "Terminal setup",
            Some("/terminal-setup"),
            Some("/terminal-setup"),
            ToolCommandFamily::BuiltIn,
            Some("Configure terminal integration"),
            "terminal",
            ToolCommandProviderKind::Claude,
            "session",
            470,
            ToolCommandCategory::PromptInsert,
            "/terminal-setup ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-vim",
            "Vim mode",
            Some("/vim"),
            Some("/vim"),
            ToolCommandFamily::BuiltIn,
            Some("Toggle vim-style input mode"),
            "keyboard",
            ToolCommandProviderKind::Claude,
            "session",
            480,
            ToolCommandCategory::PromptInsert,
            "/vim ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-review",
            "Review",
            Some("/review"),
            Some("/review"),
            ToolCommandFamily::BuiltIn,
            Some("Review recent changes"),
            "scan-search",
            ToolCommandProviderKind::Claude,
            "session",
            490,
            ToolCommandCategory::PromptInsert,
            "/review ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason,
            true,
            false,
        ),
    ]
}

fn claude_bundled_skill_commands(
    has_live_session: bool,
    detached_readonly: bool,
) -> Vec<ToolCommandCatalogItem> {
    let write_enabled = has_live_session && !detached_readonly;
    let write_reason = session_disabled_reason(has_live_session, detached_readonly, "Claude");

    vec![
        sheet_command(
            "claude-batch",
            "/batch",
            Some("/batch"),
            Some("/batch"),
            ToolCommandFamily::BundledSkill,
            Some("Orchestrate large-scale changes in parallel"),
            "layers-3",
            ToolCommandProviderKind::Claude,
            "templates",
            220,
            ToolCommandCategory::SlashTemplate,
            "/batch",
            command_sheet_arguments("/batch"),
            ToolCommandDangerLevel::Expensive,
            ToolCommandKind::BundledSkill,
            false,
            write_enabled,
            write_reason.clone(),
            true,
        ),
        text_command(
            "claude-claude-api",
            "/claude-api",
            Some("/claude-api"),
            Some("/claude-api"),
            ToolCommandFamily::BundledSkill,
            Some("Load Claude API reference material"),
            "book-open",
            ToolCommandProviderKind::Claude,
            "templates",
            230,
            ToolCommandCategory::SlashTemplate,
            "/claude-api ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::BundledSkill,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "claude-debug",
            "/debug",
            Some("/debug"),
            Some("/debug"),
            ToolCommandFamily::BundledSkill,
            Some("Troubleshoot the current Claude Code session"),
            "bug",
            ToolCommandProviderKind::Claude,
            "templates",
            240,
            ToolCommandCategory::SlashTemplate,
            "/debug ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::BundledSkill,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        sheet_command(
            "claude-loop",
            "/loop",
            Some("/loop"),
            Some("/loop"),
            ToolCommandFamily::BundledSkill,
            Some("Run a prompt repeatedly on an interval"),
            "repeat",
            ToolCommandProviderKind::Claude,
            "templates",
            250,
            ToolCommandCategory::SlashTemplate,
            "/loop",
            command_sheet_arguments("/loop"),
            ToolCommandDangerLevel::Expensive,
            ToolCommandKind::BundledSkill,
            false,
            write_enabled,
            write_reason.clone(),
            true,
        ),
        text_command(
            "claude-simplify",
            "/simplify",
            Some("/simplify"),
            Some("/simplify"),
            ToolCommandFamily::BundledSkill,
            Some("Review recent changes and apply improvements"),
            "sparkles",
            ToolCommandProviderKind::Claude,
            "templates",
            260,
            ToolCommandCategory::SlashTemplate,
            "/simplify ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::BundledSkill,
            true,
            write_enabled,
            write_reason,
            true,
            false,
        ),
    ]
}

fn codex_native_commands(
    has_live_session: bool,
    detached_readonly: bool,
) -> Vec<ToolCommandCatalogItem> {
    let write_enabled = has_live_session && !detached_readonly;
    let write_reason = session_disabled_reason(has_live_session, detached_readonly, "Codex");

    vec![
        text_command(
            "codex-new",
            "New session",
            Some("/new"),
            Some("/new"),
            ToolCommandFamily::BuiltIn,
            Some("Start a fresh interactive session"),
            "plus",
            ToolCommandProviderKind::Codex,
            "session",
            10,
            ToolCommandCategory::PromptInsert,
            "/new ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            true,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "codex-review",
            "Review",
            Some("/review"),
            Some("/review"),
            ToolCommandFamily::BuiltIn,
            Some("Run a code review"),
            "scan-search",
            ToolCommandProviderKind::Codex,
            "session",
            20,
            ToolCommandCategory::PromptInsert,
            "/review ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            true,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "codex-diff",
            "Diff",
            Some("/diff"),
            Some("/diff"),
            ToolCommandFamily::BuiltIn,
            Some("Show the current diff"),
            "git-diff",
            ToolCommandProviderKind::Codex,
            "session",
            30,
            ToolCommandCategory::PromptInsert,
            "/diff ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            true,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "codex-status",
            "Status",
            Some("/status"),
            Some("/status"),
            ToolCommandFamily::BuiltIn,
            Some("Show session status"),
            "activity",
            ToolCommandProviderKind::Codex,
            "session",
            40,
            ToolCommandCategory::PromptInsert,
            "/status ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            true,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        sheet_command(
            "codex-model",
            "Model",
            Some("/model"),
            Some("/model"),
            ToolCommandFamily::BuiltIn,
            Some("Switch the active model"),
            "cpu",
            ToolCommandProviderKind::Codex,
            "session",
            50,
            ToolCommandCategory::SlashTemplate,
            "/model",
            command_sheet_arguments("/model"),
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            true,
            write_enabled,
            write_reason.clone(),
            true,
        ),
        text_command(
            "codex-mcp",
            "MCP",
            Some("/mcp"),
            Some("/mcp"),
            ToolCommandFamily::BuiltIn,
            Some("Manage MCP servers"),
            "link",
            ToolCommandProviderKind::Codex,
            "session",
            60,
            ToolCommandCategory::PromptInsert,
            "/mcp ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            true,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "codex-plan",
            "Plan mode",
            Some("/plan"),
            Some("/plan"),
            ToolCommandFamily::BuiltIn,
            Some("Toggle plan mode"),
            "clipboard-list",
            ToolCommandProviderKind::Codex,
            "session",
            70,
            ToolCommandCategory::PromptInsert,
            "/plan ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            true,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "codex-fast-on",
            "Fast mode on",
            Some("/fast on"),
            Some("/fast on"),
            ToolCommandFamily::BuiltIn,
            Some("Enable Fast mode"),
            "zap",
            ToolCommandProviderKind::Codex,
            "session",
            80,
            ToolCommandCategory::SlashTemplate,
            "/fast on ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            true,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "codex-fast",
            "Fast mode",
            Some("/fast"),
            Some("/fast"),
            ToolCommandFamily::BuiltIn,
            Some("Toggle Fast mode"),
            "zap",
            ToolCommandProviderKind::Codex,
            "session",
            90,
            ToolCommandCategory::PromptInsert,
            "/fast ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "codex-fast-off",
            "Fast mode off",
            Some("/fast off"),
            Some("/fast off"),
            ToolCommandFamily::BuiltIn,
            Some("Disable Fast mode"),
            "zap",
            ToolCommandProviderKind::Codex,
            "session",
            100,
            ToolCommandCategory::SlashTemplate,
            "/fast off ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "codex-fast-status",
            "Fast mode status",
            Some("/fast status"),
            Some("/fast status"),
            ToolCommandFamily::BuiltIn,
            Some("Check Fast mode status"),
            "zap",
            ToolCommandProviderKind::Codex,
            "session",
            110,
            ToolCommandCategory::SlashTemplate,
            "/fast status ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "codex-permissions",
            "Permissions",
            Some("/permissions"),
            Some("/permissions"),
            ToolCommandFamily::BuiltIn,
            Some("Manage command approval and access rules"),
            "shield-check",
            ToolCommandProviderKind::Codex,
            "session",
            120,
            ToolCommandCategory::PromptInsert,
            "/permissions ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "codex-agent",
            "Agent",
            Some("/agent"),
            Some("/agent"),
            ToolCommandFamily::BuiltIn,
            Some("Switch or inspect the active agent"),
            "users",
            ToolCommandProviderKind::Codex,
            "session",
            130,
            ToolCommandCategory::PromptInsert,
            "/agent ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "codex-apps",
            "Apps",
            Some("/apps"),
            Some("/apps"),
            ToolCommandFamily::BuiltIn,
            Some("Browse app integrations"),
            "layers",
            ToolCommandProviderKind::Codex,
            "session",
            140,
            ToolCommandCategory::PromptInsert,
            "/apps ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "codex-clear",
            "Clear conversation",
            Some("/clear"),
            Some("/clear"),
            ToolCommandFamily::BuiltIn,
            Some("Clear the current conversation"),
            "eraser",
            ToolCommandProviderKind::Codex,
            "session",
            150,
            ToolCommandCategory::PromptInsert,
            "/clear ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "codex-compact",
            "Compact conversation",
            Some("/compact"),
            Some("/compact"),
            ToolCommandFamily::BuiltIn,
            Some("Compact the conversation history"),
            "minimize-2",
            ToolCommandProviderKind::Codex,
            "session",
            160,
            ToolCommandCategory::PromptInsert,
            "/compact ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "codex-copy",
            "Copy response",
            Some("/copy"),
            Some("/copy"),
            ToolCommandFamily::BuiltIn,
            Some("Copy the last assistant response"),
            "copy",
            ToolCommandProviderKind::Codex,
            "session",
            170,
            ToolCommandCategory::PromptInsert,
            "/copy ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "codex-debug-config",
            "Debug config",
            Some("/debug-config"),
            Some("/debug-config"),
            ToolCommandFamily::BuiltIn,
            Some("Inspect loaded Codex configuration"),
            "settings",
            ToolCommandProviderKind::Codex,
            "session",
            180,
            ToolCommandCategory::PromptInsert,
            "/debug-config ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "codex-exit",
            "Exit",
            Some("/exit"),
            Some("/exit"),
            ToolCommandFamily::BuiltIn,
            Some("Exit the current Codex session"),
            "log-out",
            ToolCommandProviderKind::Codex,
            "session",
            190,
            ToolCommandCategory::PromptInsert,
            "/exit ",
            true,
            ToolCommandDangerLevel::Confirm,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "codex-experimental",
            "Experimental",
            Some("/experimental"),
            Some("/experimental"),
            ToolCommandFamily::BuiltIn,
            Some("Inspect experimental features"),
            "sparkles",
            ToolCommandProviderKind::Codex,
            "session",
            200,
            ToolCommandCategory::PromptInsert,
            "/experimental ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "codex-feedback",
            "Feedback",
            Some("/feedback"),
            Some("/feedback"),
            ToolCommandFamily::BuiltIn,
            Some("Submit feedback about Codex"),
            "info",
            ToolCommandProviderKind::Codex,
            "session",
            210,
            ToolCommandCategory::PromptInsert,
            "/feedback ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "codex-fork",
            "Fork session",
            Some("/fork"),
            Some("/fork"),
            ToolCommandFamily::BuiltIn,
            Some("Fork a previous session"),
            "git-branch",
            ToolCommandProviderKind::Codex,
            "session",
            220,
            ToolCommandCategory::PromptInsert,
            "/fork ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "codex-init",
            "Initialize repository",
            Some("/init"),
            Some("/init"),
            ToolCommandFamily::BuiltIn,
            Some("Initialize Codex in this repository"),
            "sparkles",
            ToolCommandProviderKind::Codex,
            "session",
            230,
            ToolCommandCategory::PromptInsert,
            "/init ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "codex-logout",
            "Sign out",
            Some("/logout"),
            Some("/logout"),
            ToolCommandFamily::BuiltIn,
            Some("Sign out of Codex"),
            "log-out",
            ToolCommandProviderKind::Codex,
            "session",
            240,
            ToolCommandCategory::PromptInsert,
            "/logout ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "codex-mention",
            "Mention",
            Some("/mention"),
            Some("/mention"),
            ToolCommandFamily::BuiltIn,
            Some("Mention a file, path, or agent"),
            "at-sign",
            ToolCommandProviderKind::Codex,
            "session",
            250,
            ToolCommandCategory::PromptInsert,
            "/mention ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "codex-personality",
            "Personality",
            Some("/personality"),
            Some("/personality"),
            ToolCommandFamily::BuiltIn,
            Some("Adjust agent personality"),
            "sparkles",
            ToolCommandProviderKind::Codex,
            "session",
            260,
            ToolCommandCategory::PromptInsert,
            "/personality ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "codex-ps",
            "Processes",
            Some("/ps"),
            Some("/ps"),
            ToolCommandFamily::BuiltIn,
            Some("List current background tasks"),
            "terminal",
            ToolCommandProviderKind::Codex,
            "session",
            270,
            ToolCommandCategory::PromptInsert,
            "/ps ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "codex-resume",
            "Resume conversation",
            Some("/resume"),
            Some("/resume"),
            ToolCommandFamily::BuiltIn,
            Some("Resume a previous session"),
            "play",
            ToolCommandProviderKind::Codex,
            "session",
            280,
            ToolCommandCategory::PromptInsert,
            "/resume ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason.clone(),
            true,
            false,
        ),
        text_command(
            "codex-statusline",
            "Statusline",
            Some("/statusline"),
            Some("/statusline"),
            ToolCommandFamily::BuiltIn,
            Some("Customize the Codex statusline"),
            "sliders-horizontal",
            ToolCommandProviderKind::Codex,
            "session",
            290,
            ToolCommandCategory::PromptInsert,
            "/statusline ",
            true,
            ToolCommandDangerLevel::Safe,
            ToolCommandKind::ProviderNative,
            false,
            write_enabled,
            write_reason,
            true,
            false,
        ),
    ]
}

fn build_catalog_command_list(
    tool_kind: Option<AgentToolKind>,
    has_terminal_session: bool,
    detached_readonly: bool,
) -> Vec<ToolCommandCatalogItem> {
    let mut commands = Vec::new();

    match tool_kind {
        Some(AgentToolKind::Claude) => {
            commands.extend(claude_native_commands(
                has_terminal_session,
                detached_readonly,
            ));
            commands.extend(claude_bundled_skill_commands(
                has_terminal_session,
                detached_readonly,
            ));
        }
        Some(AgentToolKind::Codex) => {
            commands.extend(codex_native_commands(
                has_terminal_session,
                detached_readonly,
            ));
        }
        Some(AgentToolKind::Gemini) => {}
        Some(AgentToolKind::Shell) | Some(AgentToolKind::Unknown) | None => {
            commands.extend(claude_native_commands(
                has_terminal_session,
                detached_readonly,
            ));
            commands.extend(claude_bundled_skill_commands(
                has_terminal_session,
                detached_readonly,
            ));
            commands.extend(codex_native_commands(
                has_terminal_session,
                detached_readonly,
            ));
        }
    }

    commands.sort_by(|left, right| {
        left.priority
            .cmp(&right.priority)
            .then_with(|| left.id.cmp(&right.id))
    });
    commands
}

#[tauri::command]
pub fn tool_list_commands(
    request: ToolCommandCatalogRequest,
    state: State<'_, AppState>,
) -> Result<ToolCommandCatalogResponse, String> {
    state.workspace_root_path(&request.workspace_id)?;
    let commands = build_catalog_command_list(
        request.tool_kind,
        request.station.has_terminal_session,
        request.station.detached_readonly,
    );

    Ok(ToolCommandCatalogResponse {
        workspace_id: request.workspace_id,
        catalog_version: CATALOG_VERSION,
        tool_kind: request.tool_kind,
        station: request.station,
        commands,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_without_provider_exposes_only_native_commands() {
        let commands = build_catalog_command_list(None, false, false);
        assert!(commands.iter().any(|item| item.id == "claude-clear"));
        assert!(commands.iter().any(|item| item.id == "codex-new"));
        assert!(!commands.iter().any(|item| item.id == "launch-claude"));
        assert!(!commands.iter().any(|item| item.id == "open-providers"));
        assert!(!commands.iter().any(|item| item.id == "open-channels"));
    }

    #[test]
    fn claude_catalog_includes_aliases_effort_variants_and_skills() {
        let commands = build_catalog_command_list(Some(AgentToolKind::Claude), true, false);

        let new_command = commands
            .iter()
            .find(|item| item.id == "claude-new")
            .expect("new");
        assert_eq!(new_command.slash_command.as_deref(), Some("/new"));

        let clear = commands
            .iter()
            .find(|item| item.id == "claude-clear")
            .expect("clear");
        assert_eq!(clear.slash_command.as_deref(), Some("/clear"));

        let effort = commands
            .iter()
            .find(|item| item.id == "claude-effort")
            .expect("effort");
        assert_eq!(effort.presentation, ToolCommandPresentation::Sheet);
        assert_eq!(effort.slash_command.as_deref(), Some("/effort"));
        assert_eq!(effort.arguments.len(), 1);
        assert_eq!(effort.arguments[0].options.len(), 5);

        let effort_max = commands
            .iter()
            .find(|item| item.id == "claude-effort-max")
            .expect("effort max");
        assert_eq!(effort_max.slash_command.as_deref(), Some("/effort max"));
        assert_eq!(effort_max.command_family, ToolCommandFamily::BuiltIn);

        let loop_command = commands
            .iter()
            .find(|item| item.id == "claude-loop")
            .expect("loop");
        assert_eq!(loop_command.danger_level, ToolCommandDangerLevel::Expensive);
        assert_eq!(loop_command.command_family, ToolCommandFamily::BundledSkill);

        assert!(commands.iter().any(|item| item.id == "claude-diff"));
        assert!(commands.iter().any(|item| item.id == "claude-context"));
        assert!(commands.iter().any(|item| item.id == "claude-plan"));
    }

    #[test]
    fn codex_catalog_includes_official_native_commands() {
        let commands = build_catalog_command_list(Some(AgentToolKind::Codex), true, false);

        for id in [
            "codex-new",
            "codex-model",
            "codex-review",
            "codex-permissions",
            "codex-status",
            "codex-diff",
            "codex-fast-on",
            "codex-plan",
            "codex-agent",
            "codex-mention",
            "codex-mcp",
        ] {
            assert!(commands.iter().any(|item| item.id == id), "{id}");
        }

        let model = commands
            .iter()
            .find(|item| item.id == "codex-model")
            .expect("model");
        assert_eq!(model.presentation, ToolCommandPresentation::Sheet);
        assert_eq!(model.arguments.len(), 1);
    }

    #[test]
    fn detached_readonly_disables_provider_writes() {
        let claude_commands = build_catalog_command_list(Some(AgentToolKind::Claude), false, true);
        let help = claude_commands
            .iter()
            .find(|item| item.id == "claude-help")
            .expect("help");
        assert!(!help.enabled);
        assert_eq!(
            help.disabled_reason.as_deref(),
            Some("Detached windows are read only")
        );

        let codex_commands = build_catalog_command_list(Some(AgentToolKind::Codex), false, true);
        let review = codex_commands
            .iter()
            .find(|item| item.id == "codex-review")
            .expect("review");
        assert!(!review.enabled);
        assert_eq!(
            review.disabled_reason.as_deref(),
            Some("Detached windows are read only")
        );
    }

    #[test]
    fn command_catalog_entries_remain_slash_command_terminal_actions() {
        let commands = build_catalog_command_list(None, true, false);

        for command in commands {
            assert_eq!(
                command.surface_target,
                ToolCommandSurfaceTarget::Terminal,
                "{} surface target",
                command.id
            );
            assert_eq!(
                command.scope_kind,
                ToolCommandScopeKind::Station,
                "{} scope kind",
                command.id
            );
            assert!(
                command
                    .slash_command
                    .as_deref()
                    .is_some_and(|value| value.starts_with('/')),
                "{} slash command",
                command.id
            );
            assert!(matches!(
                command.execution,
                ToolCommandExecution::InsertText { .. }
                    | ToolCommandExecution::OpenCommandSheet { .. }
            ));

            if command.presentation == ToolCommandPresentation::Sheet {
                for argument in &command.arguments {
                    assert!(matches!(
                        argument.kind,
                        ToolCommandArgumentKind::Text
                            | ToolCommandArgumentKind::MultilineText
                            | ToolCommandArgumentKind::Enum
                            | ToolCommandArgumentKind::Duration
                            | ToolCommandArgumentKind::Path
                            | ToolCommandArgumentKind::Boolean
                    ));
                }
            }
        }
    }
}
