use crate::models::CodexProviderPreset;

use super::{
    build_codex_china_preset, build_codex_preset, build_literal_codex_preset,
    generate_codex_config_template,
};

pub fn codex_provider_presets() -> Vec<CodexProviderPreset> {
    vec![
        build_codex_preset(
            "codexOfficial",
            "codex-official",
            "aiConfig.category.global",
            "https://chatgpt.com/codex",
            "https://chatgpt.com/",
            "https://platform.openai.com/",
            "gpt-5.4",
            None,
            "",
            false,
        ),
        build_codex_preset(
            "codexAzure",
            "azure-openai",
            "aiConfig.category.global",
            "https://learn.microsoft.com/en-us/azure/ai-foundry/openai/how-to/codex",
            "https://portal.azure.com/",
            "https://portal.azure.com/",
            "gpt-5.4",
            Some("https://YOUR_RESOURCE_NAME.openai.azure.com/openai"),
            "model_provider = \"azure\"\nmodel = \"gpt-5.4\"\nmodel_reasoning_effort = \"high\"\ndisable_response_storage = true\n\n[model_providers.azure]\nname = \"Azure OpenAI\"\nbase_url = \"https://YOUR_RESOURCE_NAME.openai.azure.com/openai\"\nenv_key = \"OPENAI_API_KEY\"\nquery_params = { \"api-version\" = \"2025-04-01-preview\" }\nwire_api = \"responses\"\nrequires_openai_auth = true",
            true,
        ),
        build_codex_preset(
            "codexShengsuanyun",
            "shengsuanyun",
            "aiConfig.category.global",
            "https://www.shengsuanyun.com",
            "https://www.shengsuanyun.com/?from=CH_4HHXMRYF",
            "https://www.shengsuanyun.com",
            "gpt-5.4",
            Some("https://router.shengsuanyun.com/v1"),
            &generate_codex_config_template(
                "Shengsuanyun",
                "https://router.shengsuanyun.com/v1",
                "gpt-5.4",
            ),
            true,
        ),
        build_literal_codex_preset("aihubmix", "AiHubMix", "aiConfig.category.global", "https://aihubmix.com", "https://aihubmix.com", "https://aihubmix.com", "gpt-5.4", "https://aihubmix.com/v1"),
        build_literal_codex_preset("dmxapi", "DMXAPI", "aiConfig.category.global", "https://www.dmxapi.cn", "https://www.dmxapi.cn", "https://www.dmxapi.cn", "gpt-5.4", "https://www.dmxapi.cn/v1"),
        build_literal_codex_preset("packycode", "PackyCode", "aiConfig.category.global", "https://www.packyapi.com", "https://www.packyapi.com/register?aff=cc-switch", "https://www.packyapi.com", "gpt-5.4", "https://www.packyapi.com/v1"),
        build_literal_codex_preset("cubence", "Cubence", "aiConfig.category.global", "https://cubence.com", "https://cubence.com/signup?code=CCSWITCH&source=ccs", "https://cubence.com", "gpt-5.4", "https://api.cubence.com/v1"),
        build_literal_codex_preset("aigocode", "AIGoCode", "aiConfig.category.global", "https://aigocode.com", "https://aigocode.com/invite/CC-SWITCH", "https://aigocode.com", "gpt-5.4", "https://api.aigocode.com/v1"),
        build_literal_codex_preset("rightcode", "RightCode", "aiConfig.category.global", "https://www.right.codes", "https://www.right.codes/register?aff=CCSWITCH", "https://www.right.codes", "gpt-5.4", "https://www.right.codes/v1"),
        build_literal_codex_preset("aicodemirror", "AICodeMirror", "aiConfig.category.global", "https://www.aicodemirror.com", "https://www.aicodemirror.com/register?invitecode=9915W3", "https://www.aicodemirror.com", "gpt-5.4", "https://api.aicodemirror.com/api/v1"),
        build_literal_codex_preset("aicoding", "AICoding", "aiConfig.category.global", "https://aicoding.sh", "https://aicoding.sh/i/CCSWITCH", "https://aicoding.sh", "gpt-5.4", "https://api.aicoding.sh/v1"),
        build_literal_codex_preset("crazyrouter", "CrazyRouter", "aiConfig.category.global", "https://www.crazyrouter.com", "https://www.crazyrouter.com/register?aff=OZcm&ref=cc-switch", "https://www.crazyrouter.com", "gpt-5.4", "https://crazyrouter.com/v1"),
        build_literal_codex_preset("sssaicode", "SSSAiCode", "aiConfig.category.global", "https://www.sssaicode.com", "https://www.sssaicode.com/register?ref=DCP0SM", "https://www.sssaicode.com", "gpt-5.4", "https://node-hk.sssaicode.com/api/v1"),
        build_literal_codex_preset("compshare", "Compshare", "aiConfig.category.global", "https://www.compshare.cn", "https://www.compshare.cn/coding-plan?ytag=GPU_YY_YX_git_cc-switch", "https://www.compshare.cn", "gpt-5.4", "https://api.modelverse.cn/v1"),
        build_literal_codex_preset("compshare-coding", "Compshare Coding Plan", "aiConfig.category.global", "https://www.compshare.cn", "https://www.compshare.cn/coding-plan?ytag=GPU_YY_YX_git_cc-switch", "https://www.compshare.cn", "gpt-5.4", "https://cp.compshare.cn/v1"),
        build_literal_codex_preset("micu", "Micu", "aiConfig.category.global", "https://www.openclaudecode.cn", "https://www.openclaudecode.cn/register?aff=aOYQ", "https://www.openclaudecode.cn", "gpt-5.4", "https://www.openclaudecode.cn/v1"),
        build_literal_codex_preset("ctok", "CTok.ai", "aiConfig.category.global", "https://ctok.ai", "https://ctok.ai", "https://ctok.ai", "gpt-5.4", "https://api.ctok.ai/v1"),
        build_literal_codex_preset("lionccapi", "LionCCAPI", "aiConfig.category.global", "https://vibecodingapi.ai", "https://vibecodingapi.ai", "https://vibecodingapi.ai", "gpt-5.4", "https://vibecodingapi.ai/v1"),
        build_literal_codex_preset("ddshub", "DDSHub", "aiConfig.category.global", "https://www.ddshub.cc", "https://ddshub.short.gy/ccswitch", "https://www.ddshub.cc", "gpt-5.4", "https://www.ddshub.cc"),
        build_literal_codex_preset("e-flowcode", "E-FlowCode", "aiConfig.category.global", "https://e-flowcode.cc", "https://e-flowcode.cc", "https://e-flowcode.cc", "gpt-5.4", "https://e-flowcode.cc/v1"),
        build_literal_codex_preset("lemondata", "LemonData", "aiConfig.category.global", "https://lemondata.cc", "https://lemondata.cc/r/FFX1ZDUP", "https://lemondata.cc", "gpt-5.4", "https://api.lemondata.cc/v1"),
        build_literal_codex_preset("pipellm", "PIPELLM", "aiConfig.category.global", "https://code.pipellm.ai", "https://code.pipellm.ai/login?ref=uvw650za", "https://code.pipellm.ai", "gpt-5.4", "https://code.pipellm.ai/v1"),
        build_codex_preset("codexOpenRouter", "openrouter", "aiConfig.category.global", "https://openrouter.ai/", "https://openrouter.ai/keys", "https://openrouter.ai/", "openai/gpt-5", Some("https://openrouter.ai/api/v1"), &generate_codex_config_template("openrouter", "https://openrouter.ai/api/v1", "openai/gpt-5"), true),
        build_literal_codex_preset("therouter", "TheRouter", "aiConfig.category.global", "https://therouter.ai", "https://dashboard.therouter.ai", "https://therouter.ai", "openai/gpt-5.3-codex", "https://api.therouter.ai/v1"),
        build_codex_china_preset("codexDeepseek", "deepseek", "DeepSeek", "https://platform.deepseek.com/", "https://platform.deepseek.com/api_keys", "deepseek-chat", "https://api.deepseek.com/v1"),
        build_codex_china_preset("codexZhipuGlm", "zhipu-glm", "Zhipu GLM", "https://open.bigmodel.cn/", "https://www.bigmodel.cn/claude-code?ic=RRVJPB5SII", "glm-5", "https://open.bigmodel.cn/api/paas/v4"),
        build_codex_china_preset("codexQwenCoder", "qwen-coder", "Qwen Coder", "https://bailian.console.aliyun.com/", "https://bailian.console.aliyun.com/#/api-key", "qwen3.5-plus", "https://dashscope.aliyuncs.com/compatible-mode/v1"),
        build_codex_china_preset("codexKimiK2", "kimi-k2", "Kimi K2", "https://platform.moonshot.cn/console", "https://platform.moonshot.cn/console/api-keys", "kimi-k2.5", "https://api.moonshot.cn/v1"),
        build_codex_china_preset("codexKimiForCoding", "kimi-for-coding", "Kimi For Coding", "https://www.kimi.com/coding/docs/", "https://platform.moonshot.cn/console/api-keys", "kimi-for-coding", "https://api.kimi.com/v1"),
        build_codex_china_preset("codexMinimax", "minimax", "MiniMax", "https://platform.minimaxi.com/", "https://platform.minimaxi.com/subscribe/coding-plan", "MiniMax-M2.7", "https://api.minimaxi.com/v1"),
        build_codex_china_preset("codexDoubaoSeed", "doubaoseed", "DouBaoSeed", "https://www.volcengine.com/product/doubao", "https://www.volcengine.com/product/doubao", "doubao-seed-2-0-code-preview-latest", "https://ark.cn-beijing.volces.com/api/v3"),
        build_codex_china_preset("codexXiaomiMimo", "xiaomi-mimo", "Xiaomi MiMo", "https://platform.xiaomimimo.com/", "https://platform.xiaomimimo.com/#/console/api-keys", "mimo-v2-pro", "https://api.xiaomimimo.com/v1"),
        build_codex_china_preset("codexModelScope", "modelscope", "ModelScope", "https://modelscope.cn/", "https://modelscope.cn/my/myaccesstoken", "ZhipuAI/GLM-5", "https://api-inference.modelscope.cn/v1"),
        build_codex_china_preset("codexKatCoder", "kat-coder", "KAT-Coder", "https://console.streamlake.ai/", "https://console.streamlake.ai/console/api-key", "KAT-Coder-Pro", "https://vanchin.streamlake.ai/api/gateway/v1/endpoints/YOUR_ENDPOINT_ID/openai"),
        build_codex_china_preset("codexLongcat", "longcat", "Longcat", "https://longcat.chat/platform", "https://longcat.chat/platform/api_keys", "LongCat-Flash-Chat", "https://api.longcat.chat/v1"),
        build_codex_china_preset("codexBaiLing", "bailing", "BaiLing", "https://alipaytbox.yuque.com/sxs0ba/ling/get_started", "https://alipaytbox.yuque.com/sxs0ba/ling/get_started", "Ling-2.5-1T", "https://api.tbox.cn/v1"),
        build_codex_preset("codexCustom", "custom-gateway", "aiConfig.mode.custom", "https://platform.openai.com/docs/codex/cli", "https://platform.openai.com/api-keys", "https://platform.openai.com/", "gpt-5.4", Some("https://api.example.com/v1"), &generate_codex_config_template("custom", "https://api.example.com/v1", "gpt-5.4"), true),
    ]
}
