use std::collections::BTreeMap;

use crate::models::{ClaudeAuthScheme, ClaudeProviderPreset};

use super::{
    build_literal_claude_preset, build_preset, env_map, CLAUDE_OFFICIAL_BASE_URL,
    CLAUDE_OFFICIAL_MODEL, CLAUDE_OFFICIAL_PROVIDER_ID,
};

pub fn claude_official_provider_preset() -> ClaudeProviderPreset {
    build_preset(
        "anthropic",
        CLAUDE_OFFICIAL_PROVIDER_ID,
        "aiConfig.category.global",
        "https://console.anthropic.com/",
        "https://console.anthropic.com/settings/keys",
        "https://console.anthropic.com/",
        CLAUDE_OFFICIAL_MODEL,
        CLAUDE_OFFICIAL_BASE_URL,
        ClaudeAuthScheme::AnthropicAuthToken,
        true,
        BTreeMap::new(),
    )
}

fn claude_platform_presets() -> Vec<ClaudeProviderPreset> {
    vec![
        claude_official_provider_preset(),
        build_preset(
            "shengsuanyun",
            "shengsuanyun",
            "aiConfig.category.global",
            "https://www.shengsuanyun.com",
            "https://www.shengsuanyun.com/?from=CH_4HHXMRYF",
            "https://www.shengsuanyun.com",
            "claude-sonnet-4-20250514",
            "https://router.shengsuanyun.com/api",
            ClaudeAuthScheme::AnthropicAuthToken,
            true,
            BTreeMap::new(),
        ),
        build_preset(
            "deepseek",
            "deepseek",
            "aiConfig.category.china",
            "https://platform.deepseek.com/",
            "https://platform.deepseek.com/api_keys",
            "https://platform.deepseek.com/top_up",
            "DeepSeek-V3.2",
            "https://api.deepseek.com/anthropic",
            ClaudeAuthScheme::AnthropicAuthToken,
            true,
            BTreeMap::new(),
        ),
        build_preset(
            "zhipuGlm",
            "zhipu-glm",
            "aiConfig.category.china",
            "https://open.bigmodel.cn/",
            "https://www.bigmodel.cn/claude-code?ic=RRVJPB5SII",
            "https://open.bigmodel.cn/",
            "glm-5",
            "https://open.bigmodel.cn/api/anthropic",
            ClaudeAuthScheme::AnthropicAuthToken,
            true,
            BTreeMap::new(),
        ),
        build_preset(
            "zhipuGlmEn",
            "zhipu-glm-en",
            "aiConfig.category.global",
            "https://z.ai/",
            "https://z.ai/subscribe?ic=8JVLJQFSKB",
            "https://z.ai/",
            "glm-5",
            "https://api.z.ai/api/anthropic",
            ClaudeAuthScheme::AnthropicAuthToken,
            true,
            BTreeMap::new(),
        ),
        build_preset(
            "qwenCoder",
            "qwen-coder",
            "aiConfig.category.china",
            "https://bailian.console.aliyun.com/",
            "https://bailian.console.aliyun.com/#/api-key",
            "https://expense.console.aliyun.com/",
            "qwen3.5-plus",
            "https://coding.dashscope.aliyuncs.com/apps/anthropic",
            ClaudeAuthScheme::AnthropicAuthToken,
            true,
            BTreeMap::new(),
        ),
        build_preset(
            "kimiK2",
            "kimi-k2",
            "aiConfig.category.china",
            "https://platform.moonshot.cn/console",
            "https://platform.moonshot.cn/console/api-keys",
            "https://platform.moonshot.cn/console",
            "kimi-k2.5",
            "https://api.moonshot.cn/anthropic",
            ClaudeAuthScheme::AnthropicAuthToken,
            true,
            BTreeMap::new(),
        ),
        build_preset(
            "kimiForCoding",
            "kimi-for-coding",
            "aiConfig.category.china",
            "https://www.kimi.com/coding/docs/",
            "https://platform.moonshot.cn/console/api-keys",
            "https://platform.moonshot.cn/console",
            "kimi-for-coding",
            "https://api.kimi.com/coding/",
            ClaudeAuthScheme::AnthropicAuthToken,
            true,
            BTreeMap::new(),
        ),
        build_preset(
            "minimax",
            "minimax",
            "aiConfig.category.china",
            "https://platform.minimaxi.com/",
            "https://platform.minimaxi.com/subscribe/coding-plan",
            "https://platform.minimaxi.com/",
            "MiniMax-M2.5",
            "https://api.minimaxi.com/anthropic",
            ClaudeAuthScheme::AnthropicAuthToken,
            true,
            env_map(&[
                ("API_TIMEOUT_MS", "3000000"),
                ("CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC", "1"),
            ]),
        ),
        build_preset(
            "minimaxEn",
            "minimax-en",
            "aiConfig.category.global",
            "https://platform.minimax.io/",
            "https://platform.minimax.io/subscribe/coding-plan",
            "https://platform.minimax.io/",
            "MiniMax-M2.5",
            "https://api.minimax.io/anthropic",
            ClaudeAuthScheme::AnthropicAuthToken,
            true,
            env_map(&[
                ("API_TIMEOUT_MS", "3000000"),
                ("CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC", "1"),
            ]),
        ),
        build_preset(
            "stepFun",
            "stepfun",
            "aiConfig.category.china",
            "https://platform.stepfun.com/step-plan",
            "https://platform.stepfun.com/interface-key",
            "https://platform.stepfun.com/step-plan",
            "step-3.5-flash-2603",
            "https://api.stepfun.com/step_plan",
            ClaudeAuthScheme::AnthropicAuthToken,
            true,
            BTreeMap::new(),
        ),
        build_preset(
            "stepFunEn",
            "stepfun-en",
            "aiConfig.category.global",
            "https://platform.stepfun.ai/step-plan",
            "https://platform.stepfun.ai/interface-key",
            "https://platform.stepfun.ai/step-plan",
            "step-3.5-flash-2603",
            "https://api.stepfun.ai/step_plan",
            ClaudeAuthScheme::AnthropicAuthToken,
            true,
            BTreeMap::new(),
        ),
        build_literal_claude_preset(
            "aihubmix",
            "AiHubMix",
            "aiConfig.category.global",
            "https://aihubmix.com",
            "https://aihubmix.com",
            "https://aihubmix.com",
            "claude-sonnet-4-20250514",
            "https://aihubmix.com",
            ClaudeAuthScheme::AnthropicApiKey,
            true,
            BTreeMap::new(),
        ),
        build_literal_claude_preset(
            "siliconflow",
            "SiliconFlow",
            "aiConfig.category.china",
            "https://siliconflow.cn",
            "https://cloud.siliconflow.cn/i/drGuwc9k",
            "https://siliconflow.cn",
            "Pro/MiniMaxAI/MiniMax-M2.7",
            "https://api.siliconflow.cn",
            ClaudeAuthScheme::AnthropicAuthToken,
            true,
            BTreeMap::new(),
        ),
        build_literal_claude_preset(
            "siliconflow-en",
            "SiliconFlow en",
            "aiConfig.category.global",
            "https://siliconflow.com",
            "https://cloud.siliconflow.cn/i/drGuwc9k",
            "https://siliconflow.com",
            "MiniMaxAI/MiniMax-M2.7",
            "https://api.siliconflow.com",
            ClaudeAuthScheme::AnthropicAuthToken,
            true,
            BTreeMap::new(),
        ),
        build_literal_claude_preset(
            "dmxapi",
            "DMXAPI",
            "aiConfig.category.global",
            "https://www.dmxapi.cn",
            "https://www.dmxapi.cn",
            "https://www.dmxapi.cn",
            "claude-sonnet-4-20250514",
            "https://www.dmxapi.cn",
            ClaudeAuthScheme::AnthropicAuthToken,
            true,
            BTreeMap::new(),
        ),
    ]
}

pub fn claude_provider_presets() -> Vec<ClaudeProviderPreset> {
    let mut presets = claude_platform_presets();
    presets.extend(super::catalog_claude_partners::claude_partner_presets());
    presets.push(ClaudeProviderPreset {
        provider_id: "custom-gateway".to_string(),
        name: "aiConfig.preset.custom.name".to_string(),
        category: "aiConfig.mode.custom".to_string(),
        description: "aiConfig.preset.custom.desc".to_string(),
        website_url: "https://docs.anthropic.com/".to_string(),
        api_key_url: "https://docs.anthropic.com/".to_string(),
        billing_url: "https://docs.anthropic.com/".to_string(),
        recommended_model: "claude-3-5-sonnet-latest".to_string(),
        endpoint: "https://api.example.com/anthropic".to_string(),
        auth_scheme: ClaudeAuthScheme::AnthropicApiKey,
        why_choose: "aiConfig.preset.custom.why".to_string(),
        best_for: "aiConfig.preset.custom.bestFor".to_string(),
        requires_billing: false,
        setup_steps: vec![
            "aiConfig.preset.custom.step1".to_string(),
            "aiConfig.preset.custom.step2".to_string(),
            "aiConfig.preset.custom.step3".to_string(),
        ],
        extra_env: BTreeMap::new(),
    });
    presets
}
