use crate::models::{ClaudeAuthScheme, ClaudeProviderPreset, LightAgentGuide};

pub fn claude_provider_presets() -> Vec<ClaudeProviderPreset> {
    vec![
        ClaudeProviderPreset {
            provider_id: "anthropic-official".to_string(),
            name: "aiConfig.preset.anthropic.name".to_string(),
            category: "aiConfig.category.global".to_string(),
            description: "aiConfig.preset.anthropic.desc".to_string(),
            website_url: "https://www.anthropic.com/".to_string(),
            api_key_url: "https://console.anthropic.com/settings/keys".to_string(),
            billing_url: "https://console.anthropic.com/settings/plans".to_string(),
            recommended_model: "claude-3-5-sonnet-latest".to_string(),
            endpoint: "https://api.anthropic.com".to_string(),
            auth_scheme: ClaudeAuthScheme::AnthropicApiKey,
            why_choose: "aiConfig.preset.anthropic.why".to_string(),
            best_for: "aiConfig.preset.anthropic.bestFor".to_string(),
            requires_billing: true,
            setup_steps: vec![
                "aiConfig.preset.anthropic.step1".to_string(),
                "aiConfig.preset.anthropic.step2".to_string(),
                "aiConfig.preset.anthropic.step3".to_string(),
            ],
        },
        ClaudeProviderPreset {
            provider_id: "deepseek".to_string(),
            name: "aiConfig.preset.deepseek.name".to_string(),
            category: "aiConfig.category.china".to_string(),
            description: "aiConfig.preset.deepseek.desc".to_string(),
            website_url: "https://platform.deepseek.com/".to_string(),
            api_key_url: "https://platform.deepseek.com/api_keys".to_string(),
            billing_url: "https://platform.deepseek.com/top_up".to_string(),
            recommended_model: "deepseek-chat".to_string(),
            endpoint: "https://api.deepseek.com/anthropic".to_string(),
            auth_scheme: ClaudeAuthScheme::AnthropicApiKey,
            why_choose: "aiConfig.preset.deepseek.why".to_string(),
            best_for: "aiConfig.preset.deepseek.bestFor".to_string(),
            requires_billing: true,
            setup_steps: vec![
                "aiConfig.preset.deepseek.step1".to_string(),
                "aiConfig.preset.deepseek.step2".to_string(),
                "aiConfig.preset.deepseek.step3".to_string(),
            ],
        },
        ClaudeProviderPreset {
            provider_id: "kimi".to_string(),
            name: "aiConfig.preset.kimi.name".to_string(),
            category: "aiConfig.category.china".to_string(),
            description: "aiConfig.preset.kimi.desc".to_string(),
            website_url: "https://platform.moonshot.cn/".to_string(),
            api_key_url: "https://platform.moonshot.cn/console/api-keys".to_string(),
            billing_url: "https://platform.moonshot.cn/console/billing".to_string(),
            recommended_model: "kimi-latest".to_string(),
            endpoint: "https://api.moonshot.cn/anthropic".to_string(),
            auth_scheme: ClaudeAuthScheme::AnthropicApiKey,
            why_choose: "aiConfig.preset.kimi.why".to_string(),
            best_for: "aiConfig.preset.kimi.bestFor".to_string(),
            requires_billing: true,
            setup_steps: vec![
                "aiConfig.preset.kimi.step1".to_string(),
                "aiConfig.preset.kimi.step2".to_string(),
                "aiConfig.preset.kimi.step3".to_string(),
            ],
        },
        ClaudeProviderPreset {
            provider_id: "bailian".to_string(),
            name: "aiConfig.preset.bailian.name".to_string(),
            category: "aiConfig.category.china".to_string(),
            description: "aiConfig.preset.bailian.desc".to_string(),
            website_url: "https://bailian.console.aliyun.com/".to_string(),
            api_key_url: "https://ram.console.aliyun.com/manage/ak".to_string(),
            billing_url: "https://expense.console.aliyun.com/".to_string(),
            recommended_model: "qwen-max".to_string(),
            endpoint: "https://dashscope.aliyuncs.com/compatible-mode/anthropic".to_string(),
            auth_scheme: ClaudeAuthScheme::AnthropicApiKey,
            why_choose: "aiConfig.preset.bailian.why".to_string(),
            best_for: "aiConfig.preset.bailian.bestFor".to_string(),
            requires_billing: true,
            setup_steps: vec![
                "aiConfig.preset.bailian.step1".to_string(),
                "aiConfig.preset.bailian.step2".to_string(),
                "aiConfig.preset.bailian.step3".to_string(),
            ],
        },
        ClaudeProviderPreset {
            provider_id: "stepfun".to_string(),
            name: "aiConfig.preset.stepfun.name".to_string(),
            category: "aiConfig.category.china".to_string(),
            description: "aiConfig.preset.stepfun.desc".to_string(),
            website_url: "https://platform.stepfun.com/".to_string(),
            api_key_url: "https://platform.stepfun.com/console/api-keys".to_string(),
            billing_url: "https://platform.stepfun.com/console/billing".to_string(),
            recommended_model: "step-2-mini".to_string(),
            endpoint: "https://api.stepfun.com/anthropic".to_string(),
            auth_scheme: ClaudeAuthScheme::AnthropicApiKey,
            why_choose: "aiConfig.preset.stepfun.why".to_string(),
            best_for: "aiConfig.preset.stepfun.bestFor".to_string(),
            requires_billing: true,
            setup_steps: vec![
                "aiConfig.preset.stepfun.step1".to_string(),
                "aiConfig.preset.stepfun.step2".to_string(),
                "aiConfig.preset.stepfun.step3".to_string(),
            ],
        },
        ClaudeProviderPreset {
            provider_id: "custom-gateway".to_string(),
            name: "aiConfig.preset.custom.name".to_string(),
            category: "aiConfig.mode.custom".to_string(),
            description: "aiConfig.preset.custom.desc".to_string(),
            website_url: "https://docs.anthropic.com/".to_string(),
            api_key_url: "https://docs.anthropic.com/".to_string(),
            billing_url: "https://docs.anthropic.com/".to_string(),
            recommended_model: "claude-3-5-sonnet-latest".to_string(),
            endpoint: "https://api.example.com/anthropic".to_string(),
            auth_scheme: ClaudeAuthScheme::AnthropicApiKey,
            why_choose: "aiConfig.preset.custom.why".to_string(),
            best_for: "aiConfig.preset.custom.bestFor".to_string(),
            requires_billing: false,
            setup_steps: vec![
                "aiConfig.preset.custom.step1".to_string(),
                "aiConfig.preset.custom.step2".to_string(),
                "aiConfig.preset.custom.step3".to_string(),
            ],
        },
    ]
}

pub fn codex_light_guide() -> LightAgentGuide {
    LightAgentGuide {
        title: "aiConfig.agent.codex.title".to_string(),
        summary: "aiConfig.guide.codex.summary".to_string(),
        config_path: Some("~/.codex/config.toml".to_string()),
        docs_url: "https://platform.openai.com/docs/codex/cli".to_string(),
        tips: vec![
            "aiConfig.guide.codex.tip1".to_string(),
            "aiConfig.guide.codex.tip2".to_string(),
            "aiConfig.guide.codex.tip3".to_string(),
        ],
        config: Default::default(),
        mcp_installed: false,
    }
}

pub fn gemini_light_guide() -> LightAgentGuide {
    LightAgentGuide {
        title: "aiConfig.agent.gemini.title".to_string(),
        summary: "aiConfig.guide.gemini.summary".to_string(),
        config_path: Some("~/.gemini/settings.json".to_string()),
        docs_url: "https://github.com/google-gemini/gemini-cli".to_string(),
        tips: vec![
            "aiConfig.guide.gemini.tip1".to_string(),
            "aiConfig.guide.gemini.tip2".to_string(),
            "aiConfig.guide.gemini.tip3".to_string(),
        ],
        config: Default::default(),
        mcp_installed: false,
    }
}
