use std::collections::BTreeMap;

use crate::models::{ClaudeAuthScheme, ClaudeProviderPreset, LightAgentGuide};

pub const CLAUDE_OFFICIAL_PROVIDER_ID: &str = "anthropic-official";
pub const CLAUDE_OFFICIAL_BASE_URL: &str = "https://api.anthropic.com";
pub const CLAUDE_OFFICIAL_MODEL: &str = "claude-sonnet-4-20250514";

fn preset_key(prefix: &str, suffix: &str) -> String {
    format!("aiConfig.preset.{prefix}.{suffix}")
}

fn build_preset(
    key_prefix: &str,
    provider_id: &str,
    category: &str,
    website_url: &str,
    api_key_url: &str,
    billing_url: &str,
    recommended_model: &str,
    endpoint: &str,
    auth_scheme: ClaudeAuthScheme,
    requires_billing: bool,
    extra_env: BTreeMap<String, String>,
) -> ClaudeProviderPreset {
    ClaudeProviderPreset {
        provider_id: provider_id.to_string(),
        name: preset_key(key_prefix, "name"),
        category: category.to_string(),
        description: preset_key(key_prefix, "desc"),
        website_url: website_url.to_string(),
        api_key_url: api_key_url.to_string(),
        billing_url: billing_url.to_string(),
        recommended_model: recommended_model.to_string(),
        endpoint: endpoint.to_string(),
        auth_scheme,
        why_choose: preset_key(key_prefix, "why"),
        best_for: preset_key(key_prefix, "bestFor"),
        requires_billing,
        setup_steps: vec![
            preset_key(key_prefix, "step1"),
            preset_key(key_prefix, "step2"),
            preset_key(key_prefix, "step3"),
        ],
        extra_env,
    }
}

fn env_map(entries: &[(&str, &str)]) -> BTreeMap<String, String> {
    entries
        .iter()
        .map(|(key, value)| ((*key).to_string(), (*value).to_string()))
        .collect()
}

pub fn claude_official_provider_preset() -> ClaudeProviderPreset {
    build_preset(
        "anthropic",
        CLAUDE_OFFICIAL_PROVIDER_ID,
        "aiConfig.category.global",
        "https://console.anthropic.com/",
        "https://console.anthropic.com/settings/keys",
        "https://console.anthropic.com/",
        CLAUDE_OFFICIAL_MODEL,
        CLAUDE_OFFICIAL_BASE_URL,
        ClaudeAuthScheme::AnthropicAuthToken,
        true,
        BTreeMap::new(),
    )
}

pub fn claude_provider_presets() -> Vec<ClaudeProviderPreset> {
    vec![
        claude_official_provider_preset(),
        build_preset(
            "deepseek",
            "deepseek",
            "aiConfig.category.china",
            "https://platform.deepseek.com/",
            "https://platform.deepseek.com/api_keys",
            "https://platform.deepseek.com/top_up",
            "DeepSeek-V3.2",
            "https://api.deepseek.com/anthropic",
            ClaudeAuthScheme::AnthropicAuthToken,
            true,
            BTreeMap::new(),
        ),
        build_preset(
            "zhipuGlm",
            "zhipu-glm",
            "aiConfig.category.china",
            "https://open.bigmodel.cn/",
            "https://www.bigmodel.cn/claude-code?ic=RRVJPB5SII",
            "https://open.bigmodel.cn/",
            "glm-5",
            "https://open.bigmodel.cn/api/anthropic",
            ClaudeAuthScheme::AnthropicAuthToken,
            true,
            BTreeMap::new(),
        ),
        build_preset(
            "zhipuGlmEn",
            "zhipu-glm-en",
            "aiConfig.category.global",
            "https://z.ai/",
            "https://z.ai/subscribe?ic=8JVLJQFSKB",
            "https://z.ai/",
            "glm-5",
            "https://api.z.ai/api/anthropic",
            ClaudeAuthScheme::AnthropicAuthToken,
            true,
            BTreeMap::new(),
        ),
        build_preset(
            "qwenCoder",
            "qwen-coder",
            "aiConfig.category.china",
            "https://bailian.console.aliyun.com/",
            "https://bailian.console.aliyun.com/#/api-key",
            "https://expense.console.aliyun.com/",
            "qwen3.5-plus",
            "https://coding.dashscope.aliyuncs.com/apps/anthropic",
            ClaudeAuthScheme::AnthropicAuthToken,
            true,
            BTreeMap::new(),
        ),
        build_preset(
            "kimiK2",
            "kimi-k2",
            "aiConfig.category.china",
            "https://platform.moonshot.cn/console",
            "https://platform.moonshot.cn/console/api-keys",
            "https://platform.moonshot.cn/console",
            "kimi-k2.5",
            "https://api.moonshot.cn/anthropic",
            ClaudeAuthScheme::AnthropicAuthToken,
            true,
            BTreeMap::new(),
        ),
        build_preset(
            "kimiForCoding",
            "kimi-for-coding",
            "aiConfig.category.china",
            "https://www.kimi.com/coding/docs/",
            "https://platform.moonshot.cn/console/api-keys",
            "https://platform.moonshot.cn/console",
            "kimi-for-coding",
            "https://api.kimi.com/coding/",
            ClaudeAuthScheme::AnthropicAuthToken,
            true,
            BTreeMap::new(),
        ),
        build_preset(
            "minimax",
            "minimax",
            "aiConfig.category.china",
            "https://platform.minimaxi.com/",
            "https://platform.minimaxi.com/subscribe/coding-plan",
            "https://platform.minimaxi.com/",
            "MiniMax-M2.5",
            "https://api.minimaxi.com/anthropic",
            ClaudeAuthScheme::AnthropicAuthToken,
            true,
            env_map(&[
                ("API_TIMEOUT_MS", "3000000"),
                ("CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC", "1"),
            ]),
        ),
        build_preset(
            "minimaxEn",
            "minimax-en",
            "aiConfig.category.global",
            "https://platform.minimax.io/",
            "https://platform.minimax.io/subscribe/coding-plan",
            "https://platform.minimax.io/",
            "MiniMax-M2.5",
            "https://api.minimax.io/anthropic",
            ClaudeAuthScheme::AnthropicAuthToken,
            true,
            env_map(&[
                ("API_TIMEOUT_MS", "3000000"),
                ("CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC", "1"),
            ]),
        ),
        build_preset(
            "doubaoSeed",
            "doubaoseed",
            "aiConfig.category.china",
            "https://www.volcengine.com/product/doubao",
            "https://www.volcengine.com/product/doubao",
            "https://www.volcengine.com/product/doubao",
            "doubao-seed-2-0-code-preview-latest",
            "https://ark.cn-beijing.volces.com/api/coding",
            ClaudeAuthScheme::AnthropicAuthToken,
            true,
            env_map(&[("API_TIMEOUT_MS", "3000000")]),
        ),
        build_preset(
            "xiaomiMimo",
            "xiaomi-mimo",
            "aiConfig.category.china",
            "https://platform.xiaomimimo.com/",
            "https://platform.xiaomimimo.com/#/console/api-keys",
            "https://platform.xiaomimimo.com/",
            "mimo-v2-flash",
            "https://api.xiaomimimo.com/anthropic",
            ClaudeAuthScheme::AnthropicAuthToken,
            true,
            BTreeMap::new(),
        ),
        build_preset(
            "modelScope",
            "modelscope",
            "aiConfig.category.china",
            "https://modelscope.cn/",
            "https://modelscope.cn/my/myaccesstoken",
            "https://modelscope.cn/",
            "ZhipuAI/GLM-5",
            "https://api-inference.modelscope.cn",
            ClaudeAuthScheme::AnthropicAuthToken,
            true,
            BTreeMap::new(),
        ),
        build_preset(
            "openRouter",
            "openrouter",
            "aiConfig.category.global",
            "https://openrouter.ai/",
            "https://openrouter.ai/keys",
            "https://openrouter.ai/",
            "anthropic/claude-sonnet-4.6",
            "https://openrouter.ai/api",
            ClaudeAuthScheme::AnthropicAuthToken,
            true,
            BTreeMap::new(),
        ),
        build_preset(
            "nvidia",
            "nvidia",
            "aiConfig.category.global",
            "https://build.nvidia.com/",
            "https://build.nvidia.com/settings/api-keys",
            "https://build.nvidia.com/",
            "moonshotai/kimi-k2.5",
            "https://integrate.api.nvidia.com",
            ClaudeAuthScheme::AnthropicAuthToken,
            true,
            BTreeMap::new(),
        ),
        build_preset(
            "katCoder",
            "kat-coder",
            "aiConfig.category.china",
            "https://console.streamlake.ai/",
            "https://console.streamlake.ai/console/api-key",
            "https://console.streamlake.ai/",
            "KAT-Coder-Pro V1",
            "https://vanchin.streamlake.ai/api/gateway/v1/endpoints/YOUR_ENDPOINT_ID/claude-code-proxy",
            ClaudeAuthScheme::AnthropicAuthToken,
            true,
            BTreeMap::new(),
        ),
        build_preset(
            "longcat",
            "longcat",
            "aiConfig.category.china",
            "https://longcat.chat/platform",
            "https://longcat.chat/platform/api_keys",
            "https://longcat.chat/platform",
            "LongCat-Flash-Chat",
            "https://api.longcat.chat/anthropic",
            ClaudeAuthScheme::AnthropicAuthToken,
            true,
            env_map(&[
                ("CLAUDE_CODE_MAX_OUTPUT_TOKENS", "6000"),
                ("CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC", "1"),
            ]),
        ),
        build_preset(
            "baiLing",
            "bailing",
            "aiConfig.category.china",
            "https://alipaytbox.yuque.com/sxs0ba/ling/get_started",
            "https://alipaytbox.yuque.com/sxs0ba/ling/get_started",
            "https://alipaytbox.yuque.com/sxs0ba/ling/get_started",
            "Ling-2.5-1T",
            "https://api.tbox.cn/api/anthropic",
            ClaudeAuthScheme::AnthropicAuthToken,
            true,
            BTreeMap::new(),
        ),
        ClaudeProviderPreset {
            provider_id: "custom-gateway".to_string(),
            name: "aiConfig.preset.custom.name".to_string(),
            category: "aiConfig.mode.custom".to_string(),
            description: "aiConfig.preset.custom.desc".to_string(),
            website_url: "https://docs.anthropic.com/".to_string(),
            api_key_url: "https://docs.anthropic.com/".to_string(),
            billing_url: "https://docs.anthropic.com/".to_string(),
            recommended_model: "claude-3-5-sonnet-latest".to_string(),
            endpoint: "https://api.example.com/anthropic".to_string(),
            auth_scheme: ClaudeAuthScheme::AnthropicApiKey,
            why_choose: "aiConfig.preset.custom.why".to_string(),
            best_for: "aiConfig.preset.custom.bestFor".to_string(),
            requires_billing: false,
            setup_steps: vec![
                "aiConfig.preset.custom.step1".to_string(),
                "aiConfig.preset.custom.step2".to_string(),
                "aiConfig.preset.custom.step3".to_string(),
            ],
            extra_env: BTreeMap::new(),
        },
    ]
}

pub fn codex_light_guide() -> LightAgentGuide {
    LightAgentGuide {
        title: "aiConfig.agent.codex.title".to_string(),
        summary: "aiConfig.guide.codex.summary".to_string(),
        config_path: Some("~/.codex/config.toml".to_string()),
        docs_url: "https://platform.openai.com/docs/codex/cli".to_string(),
        tips: vec![
            "aiConfig.guide.codex.tip1".to_string(),
            "aiConfig.guide.codex.tip2".to_string(),
            "aiConfig.guide.codex.tip3".to_string(),
        ],
        config: Default::default(),
        mcp_installed: false,
    }
}

pub fn gemini_light_guide() -> LightAgentGuide {
    LightAgentGuide {
        title: "aiConfig.agent.gemini.title".to_string(),
        summary: "aiConfig.guide.gemini.summary".to_string(),
        config_path: Some("~/.gemini/settings.json".to_string()),
        docs_url: "https://github.com/google-gemini/gemini-cli".to_string(),
        tips: vec![
            "aiConfig.guide.gemini.tip1".to_string(),
            "aiConfig.guide.gemini.tip2".to_string(),
            "aiConfig.guide.gemini.tip3".to_string(),
        ],
        config: Default::default(),
        mcp_installed: false,
    }
}
